/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppGaleriaRouteImport } from './routes/app/galeria'
import { Route as AppComensalIndexRouteImport } from './routes/app/comensal/index'
import { Route as AppComensalAjustesRouteImport } from './routes/app/comensal/ajustes'
import { Route as AppComensalRestaurantesRouteImport } from './routes/app/comensal/restaurantes'
import { Route as AppDuenoIndexRouteImport } from './routes/app/dueno/index'
import { Route as AppDuenoAjustesRouteImport } from './routes/app/dueno/ajustes'
import { Route as AppDuenoCobrarRouteImport } from './routes/app/dueno/cobrar'
import { Route as AppDuenoDescontarRouteImport } from './routes/app/dueno/descontar'
import { Route as AppDuenoMenuRouteImport } from './routes/app/dueno/menu'
import { Route as AppDuenoRegistrarConsumoRouteImport } from './routes/app/dueno/registrar-consumo'
import { Route as AppDuenoPlanesIndexRouteImport } from './routes/app/dueno/planes/index'
import { Route as AppDuenoPlanesNuevoRouteImport } from './routes/app/dueno/planes/nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGaleriaRoute = AppGaleriaRouteImport.update({
  id: '/app/galeria',
  path: '/app/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComensalIndexRoute = AppComensalIndexRouteImport.update({
  id: '/app/comensal/',
  path: '/app/comensal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComensalAjustesRoute = AppComensalAjustesRouteImport.update({
  id: '/app/comensal/ajustes',
  path: '/app/comensal/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComensalRestaurantesRoute = AppComensalRestaurantesRouteImport.update({
  id: '/app/comensal/restaurantes',
  path: '/app/comensal/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoIndexRoute = AppDuenoIndexRouteImport.update({
  id: '/app/dueno/',
  path: '/app/dueno/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoAjustesRoute = AppDuenoAjustesRouteImport.update({
  id: '/app/dueno/ajustes',
  path: '/app/dueno/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoCobrarRoute = AppDuenoCobrarRouteImport.update({
  id: '/app/dueno/cobrar',
  path: '/app/dueno/cobrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoDescontarRoute = AppDuenoDescontarRouteImport.update({
  id: '/app/dueno/descontar',
  path: '/app/dueno/descontar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoMenuRoute = AppDuenoMenuRouteImport.update({
  id: '/app/dueno/menu',
  path: '/app/dueno/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoRegistrarConsumoRoute =
  AppDuenoRegistrarConsumoRouteImport.update({
    id: '/app/dueno/registrar-consumo',
    path: '/app/dueno/registrar-consumo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppDuenoPlanesIndexRoute = AppDuenoPlanesIndexRouteImport.update({
  id: '/app/dueno/planes/',
  path: '/app/dueno/planes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDuenoPlanesNuevoRoute = AppDuenoPlanesNuevoRouteImport.update({
  id: '/app/dueno/planes/nuevo',
  path: '/app/dueno/planes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/galeria': typeof AppGaleriaRoute
  '/app/': typeof AppIndexRoute
  '/app/comensal/ajustes': typeof AppComensalAjustesRoute
  '/app/comensal/restaurantes': typeof AppComensalRestaurantesRoute
  '/app/dueno/ajustes': typeof AppDuenoAjustesRoute
  '/app/dueno/cobrar': typeof AppDuenoCobrarRoute
  '/app/dueno/descontar': typeof AppDuenoDescontarRoute
  '/app/dueno/menu': typeof AppDuenoMenuRoute
  '/app/dueno/registrar-consumo': typeof AppDuenoRegistrarConsumoRoute
  '/app/comensal/': typeof AppComensalIndexRoute
  '/app/dueno/': typeof AppDuenoIndexRoute
  '/app/dueno/planes/nuevo': typeof AppDuenoPlanesNuevoRoute
  '/app/dueno/planes/': typeof AppDuenoPlanesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/galeria': typeof AppGaleriaRoute
  '/app': typeof AppIndexRoute
  '/app/comensal/ajustes': typeof AppComensalAjustesRoute
  '/app/comensal/restaurantes': typeof AppComensalRestaurantesRoute
  '/app/dueno/ajustes': typeof AppDuenoAjustesRoute
  '/app/dueno/cobrar': typeof AppDuenoCobrarRoute
  '/app/dueno/descontar': typeof AppDuenoDescontarRoute
  '/app/dueno/menu': typeof AppDuenoMenuRoute
  '/app/dueno/registrar-consumo': typeof AppDuenoRegistrarConsumoRoute
  '/app/comensal': typeof AppComensalIndexRoute
  '/app/dueno': typeof AppDuenoIndexRoute
  '/app/dueno/planes/nuevo': typeof AppDuenoPlanesNuevoRoute
  '/app/dueno/planes': typeof AppDuenoPlanesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/galeria': typeof AppGaleriaRoute
  '/app/': typeof AppIndexRoute
  '/app/comensal/ajustes': typeof AppComensalAjustesRoute
  '/app/comensal/restaurantes': typeof AppComensalRestaurantesRoute
  '/app/dueno/ajustes': typeof AppDuenoAjustesRoute
  '/app/dueno/cobrar': typeof AppDuenoCobrarRoute
  '/app/dueno/descontar': typeof AppDuenoDescontarRoute
  '/app/dueno/menu': typeof AppDuenoMenuRoute
  '/app/dueno/registrar-consumo': typeof AppDuenoRegistrarConsumoRoute
  '/app/comensal/': typeof AppComensalIndexRoute
  '/app/dueno/': typeof AppDuenoIndexRoute
  '/app/dueno/planes/nuevo': typeof AppDuenoPlanesNuevoRoute
  '/app/dueno/planes/': typeof AppDuenoPlanesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/galeria'
    | '/app/'
    | '/app/comensal/ajustes'
    | '/app/comensal/restaurantes'
    | '/app/dueno/ajustes'
    | '/app/dueno/cobrar'
    | '/app/dueno/descontar'
    | '/app/dueno/menu'
    | '/app/dueno/registrar-consumo'
    | '/app/comensal/'
    | '/app/dueno/'
    | '/app/dueno/planes/nuevo'
    | '/app/dueno/planes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/galeria'
    | '/app'
    | '/app/comensal/ajustes'
    | '/app/comensal/restaurantes'
    | '/app/dueno/ajustes'
    | '/app/dueno/cobrar'
    | '/app/dueno/descontar'
    | '/app/dueno/menu'
    | '/app/dueno/registrar-consumo'
    | '/app/comensal'
    | '/app/dueno'
    | '/app/dueno/planes/nuevo'
    | '/app/dueno/planes'
  id:
    | '__root__'
    | '/'
    | '/app/galeria'
    | '/app/'
    | '/app/comensal/ajustes'
    | '/app/comensal/restaurantes'
    | '/app/dueno/ajustes'
    | '/app/dueno/cobrar'
    | '/app/dueno/descontar'
    | '/app/dueno/menu'
    | '/app/dueno/registrar-consumo'
    | '/app/comensal/'
    | '/app/dueno/'
    | '/app/dueno/planes/nuevo'
    | '/app/dueno/planes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppGaleriaRoute: typeof AppGaleriaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComensalAjustesRoute: typeof AppComensalAjustesRoute
  AppComensalRestaurantesRoute: typeof AppComensalRestaurantesRoute
  AppDuenoAjustesRoute: typeof AppDuenoAjustesRoute
  AppDuenoCobrarRoute: typeof AppDuenoCobrarRoute
  AppDuenoDescontarRoute: typeof AppDuenoDescontarRoute
  AppDuenoMenuRoute: typeof AppDuenoMenuRoute
  AppDuenoRegistrarConsumoRoute: typeof AppDuenoRegistrarConsumoRoute
  AppComensalIndexRoute: typeof AppComensalIndexRoute
  AppDuenoIndexRoute: typeof AppDuenoIndexRoute
  AppDuenoPlanesNuevoRoute: typeof AppDuenoPlanesNuevoRoute
  AppDuenoPlanesIndexRoute: typeof AppDuenoPlanesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/galeria': {
      id: '/app/galeria'
      path: '/app/galeria'
      fullPath: '/app/galeria'
      preLoaderRoute: typeof AppGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comensal/': {
      id: '/app/comensal/'
      path: '/app/comensal'
      fullPath: '/app/comensal/'
      preLoaderRoute: typeof AppComensalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comensal/ajustes': {
      id: '/app/comensal/ajustes'
      path: '/app/comensal/ajustes'
      fullPath: '/app/comensal/ajustes'
      preLoaderRoute: typeof AppComensalAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comensal/restaurantes': {
      id: '/app/comensal/restaurantes'
      path: '/app/comensal/restaurantes'
      fullPath: '/app/comensal/restaurantes'
      preLoaderRoute: typeof AppComensalRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/': {
      id: '/app/dueno/'
      path: '/app/dueno'
      fullPath: '/app/dueno/'
      preLoaderRoute: typeof AppDuenoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/ajustes': {
      id: '/app/dueno/ajustes'
      path: '/app/dueno/ajustes'
      fullPath: '/app/dueno/ajustes'
      preLoaderRoute: typeof AppDuenoAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/cobrar': {
      id: '/app/dueno/cobrar'
      path: '/app/dueno/cobrar'
      fullPath: '/app/dueno/cobrar'
      preLoaderRoute: typeof AppDuenoCobrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/descontar': {
      id: '/app/dueno/descontar'
      path: '/app/dueno/descontar'
      fullPath: '/app/dueno/descontar'
      preLoaderRoute: typeof AppDuenoDescontarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/menu': {
      id: '/app/dueno/menu'
      path: '/app/dueno/menu'
      fullPath: '/app/dueno/menu'
      preLoaderRoute: typeof AppDuenoMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/registrar-consumo': {
      id: '/app/dueno/registrar-consumo'
      path: '/app/dueno/registrar-consumo'
      fullPath: '/app/dueno/registrar-consumo'
      preLoaderRoute: typeof AppDuenoRegistrarConsumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/planes/': {
      id: '/app/dueno/planes/'
      path: '/app/dueno/planes'
      fullPath: '/app/dueno/planes/'
      preLoaderRoute: typeof AppDuenoPlanesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dueno/planes/nuevo': {
      id: '/app/dueno/planes/nuevo'
      path: '/app/dueno/planes/nuevo'
      fullPath: '/app/dueno/planes/nuevo'
      preLoaderRoute: typeof AppDuenoPlanesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppGaleriaRoute: AppGaleriaRoute,
  AppIndexRoute: AppIndexRoute,
  AppComensalAjustesRoute: AppComensalAjustesRoute,
  AppComensalRestaurantesRoute: AppComensalRestaurantesRoute,
  AppDuenoAjustesRoute: AppDuenoAjustesRoute,
  AppDuenoCobrarRoute: AppDuenoCobrarRoute,
  AppDuenoDescontarRoute: AppDuenoDescontarRoute,
  AppDuenoMenuRoute: AppDuenoMenuRoute,
  AppDuenoRegistrarConsumoRoute: AppDuenoRegistrarConsumoRoute,
  AppComensalIndexRoute: AppComensalIndexRoute,
  AppDuenoIndexRoute: AppDuenoIndexRoute,
  AppDuenoPlanesNuevoRoute: AppDuenoPlanesNuevoRoute,
  AppDuenoPlanesIndexRoute: AppDuenoPlanesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
